import type { Metadata } from "next";
import Link from "next/link";
import { Inter } from "next/font/google";
import { DM_Sans } from "next/font/google";
import "./globals.css";

const dmSans = DM_Sans({ subsets: ["latin"] });
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="w-full bg-[#002d72] sticky top-0 z-20">
          <div className="max-w-screen-xl mx-auto flex p-4">
            <div className="logo mr-auto"><Link href="/">Logo</Link></div>
            <nav className="navigation">
              <button className="p-4 text-white">About Me</button>
              <Link href="/projects" className="p-4 text-white">Portfolio</Link>
              <button className="p-4 text-white">Contact Me</button>
            </nav>
          </div>
        </header>
        {children}
        <footer>
          <div className="text-center">Copyright 2024</div>
        </footer>
      </body>
    </html>
  );
}
